// frontend-angular/src/app/components/traje-detail/traje-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, ActivatedRoute, Router } from '@angular/router';
import { TrajeService } from '../../services/product.service';
import { Traje, MaterialInfo } from '../../models/interfaces';

@Component({
  selector: 'app-traje-detail',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <!-- Navegación -->
    <nav aria-label="breadcrumb" class="mb-4">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a routerLink="/">Inicio</a></li>
        <li class="breadcrumb-item"><a routerLink="/trajes">Trajes</a></li>
        <li class="breadcrumb-item active" *ngIf="traje">{{ traje.nombre }}</li>
      </ol>
    </nav>

    <!-- Detalle del traje -->
    <div class="row" *ngIf="traje">
      <div class="col-lg-6">
        <!-- Imagen/Vista del traje -->
        <div class="card mb-4">
          <div class="traje-visualization d-flex flex-column justify-content-center align-items-center"
               style="height: 400px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);">
            <i class="fas fa-tshirt fa-5x text-white mb-3"></i>
            <h4 class="text-white text-center">{{ traje.nombre }}</h4>
            <span class="badge bg-light text-dark fs-6 mt-2">{{ getMaterialLabel(traje.material) }}</span>
          </div>
        </div>
      </div>

      <div class="col-lg-6">
        <!-- Información del traje -->
        <div class="card">
          <div class="card-header">
            <h2 class="mb-0">{{ traje.nombre }}</h2>
          </div>
          <div class="card-body">
            <!-- Información básica -->
            <div class="row mb-3">
              <div class="col-sm-4">
                <strong>Material:</strong>
              </div>
              <div class="col-sm-8">
                <span class="badge"
                      [ngClass]="'bg-' + getMaterialColor(traje.material)">
                  <i [class]="getMaterialIcon(traje.material)" class="me-1"></i>
                  {{ getMaterialLabel(traje.material) }}
                </span>
              </div>
            </div>

            <div class="row mb-3">
              <div class="col-sm-4">
                <strong>Propietario:</strong>
              </div>
              <div class="col-sm-8">
                <i class="fas fa-user me-2 text-muted"></i>
                {{ traje.propietario }}
              </div>
            </div>

            <!-- Descripción -->
            <div class="row mb-3">
              <div class="col-sm-4">
                <strong>Descripción:</strong>
              </div>
              <div class="col-sm-8">
                <i class="fas fa-file-alt me-2 text-muted"></i>
                <span>{{ traje.descripcion }}</span>
              </div>
            </div>

            <!-- Precio -->
            <div class="row mb-3">
              <div class="col-sm-4">
                <strong>Precio:</strong>
              </div>
              <div class="col-sm-8">
                <i class="fas fa-euro-sign me-2 text-success"></i>
                <span class="text-success fw-bold fs-5">{{ traje.precio | currency:'EUR':'symbol':'1.2-2' }}</span>
              </div>
            </div>

            <!-- Disponibilidad -->
            <div class="row mb-3">
              <div class="col-sm-4">
                <strong>Disponibilidad:</strong>
              </div>
              <div class="col-sm-8">
                <span *ngIf="traje.disponible" class="badge bg-success">
                  <i class="fas fa-check me-1"></i>Disponible
                </span>
                <span *ngIf="!traje.disponible" class="badge bg-danger">
                  <i class="fas fa-times me-1"></i>No disponible
                </span>
              </div>
            </div>
            <div class="row mb-3" *ngIf="traje.createdAt">
              <div class="col-sm-4">
                <strong>Registrado:</strong>
              </div>
              <div class="col-sm-8">
                <i class="fas fa-calendar-plus me-2 text-muted"></i>
                {{ formatDate(traje.createdAt) }}
              </div>
            </div>

            <div class="row mb-3" *ngIf="traje.updatedAt && traje.updatedAt !== traje.createdAt">
              <div class="col-sm-4">
                <strong>Última modificación:</strong>
              </div>
              <div class="col-sm-8">
                <i class="fas fa-edit me-2 text-muted"></i>
                {{ formatDate(traje.updatedAt) }}
              </div>
            </div>

            <!-- ID del traje (para referencia) -->
            <div class="row mb-3" *ngIf="traje._id">
              <div class="col-sm-4">
                <strong>ID:</strong>
              </div>
              <div class="col-sm-8">
                <code class="text-muted small">{{ traje._id }}</code>
              </div>
            </div>

            <!-- Acciones -->
            <div class="d-flex gap-2 mt-4">
              <a [routerLink]="['/trajes/edit', traje._id]" 
                 class="btn btn-warning">
                <i class="fas fa-edit me-2"></i>
                Editar
              </a>
              <button class="btn btn-danger" 
                      (click)="deleteTraje()">
                <i class="fas fa-trash me-2"></i>
                Eliminar
              </button>
              <a routerLink="/trajes" 
                 class="btn btn-secondary ms-auto">
                <i class="fas fa-arrow-left me-2"></i>
                Volver
              </a>
            </div>
          </div>
        </div>

        <!-- Información adicional -->
        <div class="card mt-4">
          <div class="card-header">
            <h5 class="mb-0">
              <i class="fas fa-info-circle me-2"></i>
              Información adicional
            </h5>
          </div>
          <div class="card-body">
            <p class="text-muted mb-2">
              <strong>Cuidados del material:</strong>
            </p>
            <div class="alert alert-info">
              {{ getMaterialCare(traje.material) }}
            </div>
            
            <p class="text-muted mb-2 mt-3">
              <strong>Historia del traje:</strong>
            </p>
            <div class="timeline">
              <div class="timeline-item" *ngIf="traje.createdAt">
                <div class="timeline-marker bg-success"></div>
                <div class="timeline-content">
                  <h6>Registro inicial</h6>
                  <p class="text-muted small">{{ formatDate(traje.createdAt) }}</p>
                </div>
              </div>
              <div class="timeline-item" *ngIf="traje.updatedAt && traje.updatedAt !== traje.createdAt">
                <div class="timeline-marker bg-warning"></div>
                <div class="timeline-content">
                  <h6>Última modificación</h6>
                  <p class="text-muted small">{{ formatDate(traje.updatedAt) }}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Estado de carga -->
    <div class="text-center" *ngIf="loading">
      <div class="loading-spinner">
        <div class="spinner-border text-primary" role="status">
          <span class="visually-hidden">Cargando traje...</span>
        </div>
      </div>
    </div>

    <!-- Error -->
    <div class="text-center py-5" *ngIf="!loading && !traje">
      <i class="fas fa-exclamation-triangle fa-3x text-warning mb-3"></i>
      <h4>Traje no encontrado</h4>
      <p class="text-muted">El traje que buscas no existe o ha sido eliminado.</p>
      <a routerLink="/trajes" class="btn btn-primary">
        <i class="fas fa-arrow-left me-2"></i>
        Volver a Trajes
      </a>
    </div>
  `,
  styles: [`
    .card {
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
      border: none;
    }
    
    .traje-visualization {
      border-radius: 0.375rem;
    }
    
    .loading-spinner {
      padding: 3rem;
    }
    
    .timeline {
      position: relative;
      padding-left: 30px;
    }
    
    .timeline::before {
      content: '';
      position: absolute;
      left: 15px;
      top: 0;
      bottom: 0;
      width: 2px;
      background: #dee2e6;
    }
    
    .timeline-item {
      position: relative;
      margin-bottom: 20px;
    }
    
    .timeline-marker {
      position: absolute;
      left: -23px;
      top: 5px;
      width: 16px;
      height: 16px;
      border-radius: 50%;
      border: 3px solid white;
      z-index: 1;
    }
    
    .timeline-content {
      background: #f8f9fa;
      padding: 10px 15px;
      border-radius: 5px;
    }
    
    .timeline-content h6 {
      margin: 0 0 5px 0;
    }
    
    .breadcrumb-item + .breadcrumb-item::before {
      content: ">";
    }
    
    .breadcrumb a {
      text-decoration: none;
    }
    
    .breadcrumb a:hover {
      text-decoration: underline;
    }
    
    @media (max-width: 768px) {
      .d-flex.gap-2 {
        flex-direction: column;
      }
      
      .ms-auto {
        margin-left: auto !important;
        margin-top: 10px;
      }
    }
  `]
})
export class TrajeDetailComponent implements OnInit {
  traje: Traje | null = null;
  loading = true;
  materiales: MaterialInfo[] = [];

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private trajeService: TrajeService
  ) {}

  ngOnInit(): void {
    this.loadMateriales();
    this.loadTraje();
  }

  loadMateriales(): void {
    this.materiales = this.trajeService.getMateriales();
  }

  loadTraje(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (!id) {
      this.router.navigate(['/trajes']);
      return;
    }

    this.loading = true;
    this.trajeService.getTrajeById(id).subscribe({
      next: (traje) => {
        this.traje = traje;
        this.loading = false;
      },
      error: (error) => {
        console.error('Error loading traje:', error);
        this.loading = false;
      }
    });
  }

  getMaterialLabel(material: string): string {
    const mat = this.materiales.find(m => 
      m.key === material.toLowerCase() || m.label.toLowerCase() === material.toLowerCase()
    );
    return mat ? mat.label : material;
  }

  getMaterialColor(material: string): string {
    const mat = this.materiales.find(m => 
      m.key === material.toLowerCase() || m.label.toLowerCase() === material.toLowerCase()
    );
    return mat ? mat.color : 'secondary';
  }

  getMaterialIcon(material: string): string {
    const mat = this.materiales.find(m => 
      m.key === material.toLowerCase() || m.label.toLowerCase() === material.toLowerCase()
    );
    return mat ? mat.icon : 'fas fa-question';
  }

  getMaterialCare(material: string): string {
    const careInstructions: { [key: string]: string } = {
      'seda': 'Lavado en seco únicamente. Evitar la exposición directa al sol. Planchar a temperatura baja.',
      'brocado': 'Lavado profesional recomendado. Guardar en lugar seco y ventilado. Evitar doblar los bordados.',
      'terciopelo': 'Lavado en seco. Cepillar suavemente en dirección del pelo. Colgar para evitar aplastamiento.',
      'raso': 'Lavado delicado o en seco. Planchar del revés a temperatura media. Evitar el contacto con objetos rugosos.',
      'tafetan': 'Lavado en seco recomendado. Planchar mientras esté ligeramente húmedo. Guardar colgado.',
      'damasco': 'Lavado profesional. Evitar frotar los dibujos. Planchar del revés a temperatura baja.',
      'algodon': 'Lavado a máquina permitido. Planchar a temperatura alta. Fácil mantenimiento.',
      'lino': 'Lavado a máquina o manual. Se arruga fácilmente, planchar húmedo. Muy duradero.'
    };

    const key = material.toLowerCase();
    return careInstructions[key] || 'Seguir las instrucciones de cuidado del fabricante. Consultar con un especialista en textiles si tiene dudas.';
  }

  formatDate(dateString: string): string {
    const date = new Date(dateString);
    return date.toLocaleString('es-ES', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  }

  deleteTraje(): void {
    if (!this.traje) return;

    if (confirm(`¿Estás seguro de que quieres eliminar el traje "${this.traje.nombre}"?\\n\\nEsta acción no se puede deshacer.`)) {
      this.trajeService.deleteTraje(this.traje._id!).subscribe({
        next: (success) => {
          if (success) {
            alert('Traje eliminado correctamente');
            this.router.navigate(['/trajes']);
          } else {
            alert('Error al eliminar el traje');
          }
        },
        error: (error) => {
          console.error('Error deleting traje:', error);
          alert('Error al eliminar el traje');
        }
      });
    }
  }
}

// frontend-react/src/components/TrajeDetail.tsx
import React, { useState, useEffect } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { useTrajes } from '../hooks/useTrajes';
import { Traje } from '../types';


const TrajeDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { getTrajeById, deleteTraje } = useTrajes();
 
  const [traje, setTraje] = useState<Traje | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string>('');


  useEffect(() => {
    if (!id) return;
   
    const fetchTraje = async (): Promise<void> => {
      try {
        setLoading(true);
        const trajeData = await getTrajeById(id);
        if (trajeData) {
          setTraje(trajeData);
        }
      } catch (err) {
        setError(`Error al cargar el traje: ${(err as Error).message}`);
      } finally {
        setLoading(false);
      }
    };


    fetchTraje();
  }, [id, getTrajeById]);


  const handleDelete = async (): Promise<void> => {
    if (traje && window.confirm(`¿Estás seguro de que quieres eliminar el traje "${traje.nombre}"?`)) {
      try {
        if (id) {
          await deleteTraje(id);
          navigate('/trajes');
        }
      } catch (error) {
        alert(`Error al eliminar el traje: ${(error as Error).message}`);
      }
    }
  };


  const formatDate = (dateString: string): string => {
    return new Date(dateString).toLocaleDateString('es-ES', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };


  const getMaterialIcon = (material: string): string => {
    const materialIcons: Record<string, string> = {
      'Seda': 'fas fa-gem',
      'Terciopelo': 'fas fa-crown',
      'Raso': 'fas fa-star',
      'Brocado': 'fas fa-award',
      'Lentejuela': 'fas fa-sparkles',
      'Damasco': 'fas fa-leaf',
      'Faille': 'fas fa-wave-square',
      'Tul': 'fas fa-cloud',
      'Gasa': 'fas fa-feather'
    };
    return materialIcons[material] || 'fas fa-fabric';
  };


  if (loading) {
    return (
      <div className="text-center py-5">
        <div className="spinner-border text-primary" role="status">
          <span className="visually-hidden">Cargando...</span>
        </div>
        <p className="mt-2">Cargando detalles del traje...</p>
      </div>
    );
  }


  if (error) {
    return (
      <div className="alert alert-danger" role="alert">
        <h4 className="alert-heading">Error</h4>
        <p>{error}</p>
        <Link to="/trajes" className="btn btn-outline-danger">
          <i className="fas fa-arrow-left me-2"></i>Volver a la lista
        </Link>
      </div>
    );
  }


  if (!traje) {
    return (
      <div className="text-center py-5">
        <i className="fas fa-exclamation-triangle text-warning" style={{ fontSize: '80px' }}></i>
        <h4 className="mt-3">Traje no encontrado</h4>
        <p>El traje que buscas no existe o ha sido eliminado.</p>
        <Link to="/trajes" className="btn btn-primary">
          <i className="fas fa-arrow-left me-2"></i>Volver a la lista
        </Link>
      </div>
    );
  }


  return (
    <div>
      {/* Navegación */}
      <nav aria-label="breadcrumb" className="mb-4">
        <ol className="breadcrumb">
          <li className="breadcrumb-item">
            <Link to="/trajes" className="text-decoration-none">
              <i className="fas fa-list me-1"></i>Trajes
            </Link>
          </li>
          <li className="breadcrumb-item active" aria-current="page">
            {traje.nombre}
          </li>
        </ol>
      </nav>


      <div className="row">
        {/* Información principal del traje */}
        <div className="col-lg-8">
          <div className="card border-0 shadow-lg">
            <div className="card-header bg-gradient-primary text-white">
              <div className="d-flex justify-content-between align-items-center">
                <h2 className="card-title mb-0">
                  <i className="fas fa-tshirt me-2"></i>
                  {traje.nombre}
                </h2>
                <span className="badge bg-light text-dark fs-6">
                  ID: {traje._id}
                </span>
              </div>
            </div>
            <div className="card-body p-4">
              {/* Información principal */}
              <div className="row mb-4">
                <div className="col-md-6 mb-3">
                  <h5 className="text-muted mb-2">
                    <i className={`${getMaterialIcon(traje.material)} me-2 text-info`}></i>
                    Material
                  </h5>
                  <p className="h4 text-info">
                    <span className="badge bg-info text-dark p-3 rounded-3">
                      {traje.material}
                    </span>
                  </p>
                </div>
                <div className="col-md-6 mb-3">
                  <h5 className="text-muted mb-2">
                    <i className="fas fa-user me-2 text-success"></i>
                    Propietario
                  </h5>
                  <p className="h4 text-success">
                    <span className="badge bg-success p-3 rounded-3">
                      {traje.propietario}
                    </span>
                  </p>
                </div>
              </div>


              {/* Descripción */}
              <div className="mb-4 p-3 bg-light rounded">
                <h5 className="text-muted mb-3">
                  <i className="fas fa-pen me-2 text-secondary"></i>
                  Descripción
                </h5>
                <p className="text-dark" style={{ whiteSpace: 'pre-wrap' }}>
                  {traje.descripcion || 'Sin descripción disponible'}
                </p>
              </div>


              {/* Precio y Disponibilidad */}
              <div className="row mb-4">
                <div className="col-md-6">
                  <h5 className="text-muted mb-2">
                    <i className="fas fa-euro-sign me-2 text-warning"></i>
                    Precio
                  </h5>
                  <p className="h3 text-warning">
                    <span className="badge bg-warning text-dark p-3 rounded-3">
                      €{traje.precio ? traje.precio.toFixed(2) : '0.00'}
                    </span>
                  </p>
                </div>
                <div className="col-md-6">
                  <h5 className="text-muted mb-2">
                    <i className={`fas ${traje.disponible ? 'fa-check-circle me-2 text-success' : 'fa-times-circle me-2 text-danger'}`}></i>
                    Estado de Disponibilidad
                  </h5>
                  <p className="h4">
                    <span className={`badge ${traje.disponible ? 'bg-success' : 'bg-danger'} p-3 rounded-3`}>
                      {traje.disponible ? '✓ Disponible' : '✗ No disponible'}
                    </span>
                  </p>
                </div>
              </div>


              {/* Metadatos */}
              <div className="border-top pt-4">
                <h5 className="text-muted mb-3">
                  <i className="fas fa-info-circle me-2"></i>
                  Información de registro
                </h5>
                <div className="row">
                  <div className="col-md-6 mb-3">
                    <div className="d-flex align-items-center text-muted">
                      <i className="fas fa-calendar-plus me-2 text-primary"></i>
                      <div>
                        <strong>Fecha de creación:</strong><br />
                        <small>{formatDate(traje.createdAt)}</small>
                      </div>
                    </div>
                  </div>
                  <div className="col-md-6 mb-3">
                    <div className="d-flex align-items-center text-muted">
                      <i className="fas fa-edit me-2 text-warning"></i>
                      <div>
                        <strong>Última actualización:</strong><br />
                        <small>
                          {traje.updatedAt !== traje.createdAt
                            ? formatDate(traje.updatedAt)
                            : 'No modificado'
                          }
                        </small>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>


        {/* Panel de acciones */}
        <div className="col-lg-4">
          <div className="card border-0 shadow">
            <div className="card-header bg-light">
              <h5 className="card-title mb-0">
                <i className="fas fa-tools me-2"></i>
                Acciones
              </h5>
            </div>
            <div className="card-body">
              <div className="d-grid gap-2">
                <Link
                  to={`/trajes/edit/${traje._id}`}
                  className="btn btn-warning btn-lg"
                >
                  <i className="fas fa-edit me-2"></i>
                  Editar Traje
                </Link>
               
                <button
                  className="btn btn-danger btn-lg"
                  onClick={handleDelete}
                >
                  <i className="fas fa-trash me-2"></i>
                  Eliminar Traje
                </button>
               
                <hr className="my-3" />
               
                <Link
                  to="/trajes"
                  className="btn btn-outline-secondary"
                >
                  <i className="fas fa-arrow-left me-2"></i>
                  Volver a la lista
                </Link>
               
                <Link
                  to="/trajes/add"
                  className="btn btn-outline-primary"
                >
                  <i className="fas fa-plus me-2"></i>
                  Añadir nuevo traje
                </Link>
              </div>
            </div>
          </div>


          {/* Información adicional */}
          <div className="card border-0 shadow mt-4">
            <div className="card-header bg-light">
              <h6 className="card-title mb-0">
                <i className="fas fa-lightbulb me-2 text-warning"></i>
                Información
              </h6>
            </div>
            <div className="card-body">
              <p className="small text-muted mb-2">
                <strong>Los trajes falleros</strong> son parte del patrimonio cultural valenciano.
                Cada uno tiene sus propias características según el material y la tradición.
              </p>
              <p className="small text-muted mb-0">
                Recuerda mantener actualizada la información del propietario y el estado del traje.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};


export default TrajeDetail;
